enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "module"
excluded-patches = "'Custom branding name for YouTube' 'Custom branding icon for YouTube' 'Custom package name'"
included-patches = ""
version = "19.16.39"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Extended]
app-name = "YouTube"
excluded-patches = "'Custom branding name for YouTube' 'Custom branding icon for YouTube' 'Custom package name'"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "Youtube"
build-mode = "module"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
